services:
  db:
    image: postgres:15
    container_name: stude_db
    ports:
      - "5432:5432"
    env_file:
      - .env
  python_app:
    build:
      dockerfile: docker/dockerfile
      context: ..
    container_name: python_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes: #Volume para manter app no disco para não ter que buildar toda vez que mudar o código
      - ../:/pastadocker
      #executa streamlit ao buildar container e adiciona parâmetro de monitoramento de atualização
      # de código
    command: sh -c "streamlit run app.py --server.fileWatcherType poll" 